"""
{corpus_name} Retriever for ATLAS

This retriever implementation was auto-generated by the ATLAS Corpus Wizard
on {creation_date} at {creation_time}.

Configuration:
- Corpus Name: {corpus_name}
- Filter 1: {filter_1_label}
- Filter 2: {filter_2_label}
- Embedding Model: {embedding_model}
- Vector Store: ChromaDB
"""

import os
import logging
from typing import Dict, List, Any, Optional
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document

from backend.retrievers.base_retriever import BaseRetriever
from backend.modules.manifest_loader import load_manifest

# Configure logging
logger = logging.getLogger(__name__)

class {CorpusClass}Retriever(BaseRetriever):
    """
    Retriever implementation for {corpus_name}.

    This retriever supports the 2-filter system with:
    - filter_1: {filter_1_label}
    - filter_2: {filter_2_label}

    It also supports optional enrichment metadata fields if configured.
    """

    def __init__(self, config: Dict[str, Any]):
        """Initialize the {corpus_name} retriever."""
        super().__init__(config)

        # Load manifest for filter options
        self.manifest = load_manifest()

        # Initialize ChromaDB connection
        persist_directory = config.get("chroma_persist_directory", "backend/corpus/chroma_db")
        collection_name = config.get("chroma_collection_name", "{corpus_name}_collection")

        # Initialize embedding model
        model_name = config.get("embedding_model", "{embedding_model}")
        model_kwargs = {{'device': 'cpu'}}
        encode_kwargs = {{'normalize_embeddings': True}}

        self.embeddings = HuggingFaceEmbeddings(
            model_name=model_name,
            model_kwargs=model_kwargs,
            encode_kwargs=encode_kwargs
        )

        # Initialize vector store
        self.vector_store = Chroma(
            collection_name=collection_name,
            embedding_function=self.embeddings,
            persist_directory=persist_directory
        )

        # Store configuration
        self.supports_filtering = True
        self.filter_1_label = "{filter_1_label}"
        self.filter_2_label = "{filter_2_label}"

    def get_retriever(self):
        """Return the ChromaDB retriever."""
        return self.vector_store.as_retriever(
            search_type=self.search_type,
            search_kwargs=self.search_kwargs
        )

    def get_config(self) -> Dict[str, Any]:
        """Return the complete configuration."""
        return {{
            "corpus_name": "{corpus_name}",
            "filter_1_label": self.filter_1_label,
            "filter_2_label": self.filter_2_label,
            "embedding_model": self.embedding_model,
            "search_type": self.search_type,
            "search_kwargs": self.search_kwargs,
            "supports_corpus_filtering": True,
            "corpus_options": self.get_corpus_options()
        }}

    @property
    def supports_corpus_filtering(self) -> bool:
        """This retriever supports 2-filter filtering."""
        return True

    def get_corpus_options(self) -> List[Dict[str, str]]:
        """Get available filter options from manifest."""
        options = []

        # Add "All" option
        options.append({{"value": "all", "label": "All Collections"}})

        # Get filter_1 options from manifest
        if self.manifest and "filters" in self.manifest:
            for filter_def in self.manifest["filters"]:
                if filter_def.get("id") == "filter_1":
                    for value in filter_def.get("values", []):
                        options.append({{
                            "value": value,
                            "label": value.replace("_", " ").title()
                        }})

        return options

    async def _get_relevant_documents(
        self,
        query: str,
        **kwargs: Any,
    ) -> List[Document]:
        """
        Retrieve relevant documents with optional 2-filter filtering.

        Args:
            query: The search query
            **kwargs: Additional arguments including filters

        Returns:
            List of relevant documents
        """
        # Build filter dictionary for ChromaDB
        filter_dict = {{}}

        # Extract filter values from kwargs
        config = kwargs.get("config", {{}})

        # Handle filter_1
        filter_1 = config.get("filter_1")
        if filter_1 and filter_1 != "all":
            filter_dict["filter_1"] = filter_1

        # Handle filter_2
        filter_2 = config.get("filter_2")
        if filter_2 and filter_2 != "all":
            filter_dict["filter_2"] = filter_2

        # Perform the search
        k = kwargs.get("k", self.search_kwargs.get("k", 10))

        if filter_dict:
            # Search with filters
            docs = self.vector_store.similarity_search(
                query=query,
                k=k,
                filter=filter_dict
            )
        else:
            # Search without filters
            docs = self.vector_store.similarity_search(
                query=query,
                k=k
            )

        # Log retrieval info
        logger.info(f"Retrieved {{len(docs)}} documents for query: {{query[:50]}}...")
        if filter_dict:
            logger.info(f"Applied filters: {{filter_dict}}")

        return docs

    def invoke(self, query: str, config: Optional[Dict] = None, k: int = 10) -> List[Document]:
        """
        Synchronous method to retrieve documents.

        This method is provided for backward compatibility and testing.
        """
        import asyncio
        return asyncio.run(self._get_relevant_documents(
            query=query,
            config=config,
            k=k
        ))