"""
new2 Retriever for ATLAS

This retriever implementation was auto-generated by the ATLAS Corpus Wizard
on 2026-02-02 at 18:09:40.

Configuration:
- Corpus Name: new2
- Filter 1: All Documents
- Filter 2: United Kingdom
- Embedding Model: Livingwithmachines/bert_1890_1900
- Vector Store: ChromaDB
"""

import os
import logging
from typing import Dict, List, Any, Optional
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document

from backend.retrievers.base_retriever import BaseRetriever
from backend.modules.manifest_loader import load_manifest
from backend.modules.llm import create_llm

# Configure logging
logger = logging.getLogger(__name__)

class New2Retriever(BaseRetriever):
    """
    Retriever implementation for new2.

    This retriever supports the 2-filter system with:
    - filter_1: All Documents
    - filter_2: United Kingdom

    It also supports optional enrichment metadata fields if configured.
    """

    def __init__(self, config: Dict[str, Any]):
        """Initialize the new2 retriever."""
        super().__init__(config)

        # Load manifest for filter options
        self.manifest = load_manifest()

        # Store corpus IDs for balanced search operations
        self._corpus_ids = []
        if self.manifest and "fields" in self.manifest and "corpus" in self.manifest["fields"]:
            values = self.manifest["fields"]["corpus"].get("values", [])
            self._corpus_ids = [v for v in values if v != "all"]

        # Store LARGE_RETRIEVAL_SIZE values for balanced retrieval
        self.large_single = config.get("LARGE_RETRIEVAL_SIZE_SINGLE_CORPUS", 120)
        self.large_all = config.get("LARGE_RETRIEVAL_SIZE_ALL_CORPUS", 80)

        # Initialize ChromaDB connection
        persist_directory = config.get("chroma_persist_directory", "backend/corpus/chroma_db")
        collection_name = config.get("chroma_collection_name", "new2_c")

        # Initialize embedding model
        model_name = config.get("embedding_model", "Livingwithmachines/bert_1890_1900")
        model_kwargs = {'device': 'cpu'}
        encode_kwargs = {'normalize_embeddings': True}

        self.embeddings = HuggingFaceEmbeddings(
            model_name=model_name,
            model_kwargs=model_kwargs,
            encode_kwargs=encode_kwargs
        )

        # Initialize vector store
        self.vector_store = Chroma(
            collection_name=collection_name,
            embedding_function=self.embeddings,
            persist_directory=persist_directory
        )

        # Initialize LLM
        provider = config.get("llm_provider", "anthropic")
        model = config.get("llm_model", "claude-3-5-haiku-20241022")
        try:
            self.llm = create_llm(provider=provider, model_name=model)
            logger.info(f"Initialized LLM: {provider}/{model}")
        except Exception as e:
            logger.warning(f"Failed to initialize LLM: {e}. LLM features will be unavailable.")
            self.llm = None

        # Store configuration
        self.supports_filtering = True
        self.filter_1_label = "All Documents"
        self.filter_2_label = "United Kingdom"

    def get_retriever(self):
        """Return the ChromaDB retriever."""
        return self.vector_store.as_retriever(
            search_type=self.search_type,
            search_kwargs=self.search_kwargs
        )

    def get_config(self) -> Dict[str, Any]:
        """Return the complete configuration."""
        return {
            "corpus_name": "new2",
            "filter_1_label": self.filter_1_label,
            "filter_2_label": self.filter_2_label,
            "embedding_model": self.embedding_model,
            "search_type": self.search_type,
            "search_kwargs": self.search_kwargs,
            "supports_corpus_filtering": True,
            "corpus_options": self.get_corpus_options()
        }

    @property
    def supports_corpus_filtering(self) -> bool:
        """This retriever supports 2-filter filtering."""
        return True

    def get_corpus_options(self) -> List[Dict[str, str]]:
        """Get available filter options from manifest."""
        options = []

        # Add "All" option
        options.append({"value": "all", "label": "All Collections"})

        # Get filter options from manifest.fields.corpus.values
        if self.manifest:
            # Try new manifest structure first (fields.corpus.values)
            if "fields" in self.manifest and "corpus" in self.manifest["fields"]:
                corpus_field = self.manifest["fields"]["corpus"]
                if "values" in corpus_field:
                    for value in corpus_field["values"]:
                        # Skip 'all' since we already added it as "All Collections"
                        if value == "all":
                            continue
                        # Create a human-readable label from the value
                        label = value.replace("_", " ").title() if isinstance(value, str) else str(value)
                        options.append({
                            "value": value,
                            "label": label
                        })
            # Fallback to legacy structure for backward compatibility
            elif "filters" in self.manifest:
                for filter_def in self.manifest["filters"]:
                    if filter_def.get("id") == "filter_1":
                        for value in filter_def.get("values", []):
                            options.append({
                                "value": value,
                                "label": value.replace("_", " ").title()
                            })

        return options

    def _candidate_pool_size(self, corpus_filter: Optional[str]) -> int:
        """Decide how many candidates to fetch for retrieval.

        - If a specific corpus is selected: use LARGE_RETRIEVAL_SIZE_SINGLE_CORPUS
        - If 'all' or not specified: use LARGE_RETRIEVAL_SIZE_ALL_CORPUS
        Always floor to 10x the configured search_k to preserve recall.
        """
        is_all = (not corpus_filter) or (corpus_filter == "all")
        base = self.large_all if is_all else self.large_single
        return max(base, self.search_kwargs.get("k", 20) * 10)

    def _per_corpus_candidate_size(self, corpus_filter: Optional[str]) -> int:
        """Calculate candidates per corpus for balanced retrieval."""
        if corpus_filter and corpus_filter != "all":
            # Single corpus - use full allocation
            return self._candidate_pool_size(corpus_filter)

        # Multi-corpus - divide pool across corpora for balance
        total_pool = self._candidate_pool_size(corpus_filter)
        corpora_count = len(self._corpus_ids) if self._corpus_ids else 1
        per_corpus = total_pool // corpora_count
        return max(per_corpus, self.search_kwargs.get("k", 20))

    def _ensure_balanced_final_selection(self, docs: List[Document], target_k: int, corpus_filter: Optional[str]) -> List[Document]:
        """Apply stratified final selection to ensure balanced corpus representation."""
        if corpus_filter and corpus_filter != "all":
            # Single corpus - no balancing needed
            return docs[:target_k]

        if not docs or not self._corpus_ids:
            return docs[:target_k]

        # Group documents by corpus
        corpus_docs = {cid: [] for cid in self._corpus_ids}
        unknown_docs = []

        for doc in docs:
            corpus = doc.metadata.get("filter_1", doc.metadata.get("corpus"))
            if corpus in corpus_docs:
                corpus_docs[corpus].append(doc)
            else:
                unknown_docs.append(doc)

        # Calculate target per corpus (roughly equal distribution)
        corpora_count = len(self._corpus_ids)
        per_corpus_target = max(1, target_k // corpora_count)  # At least 1 per corpus
        remainder = target_k % corpora_count

        # Build balanced selection
        balanced_selection = []

        # First pass: take target amount from each corpus
        for corpus in self._corpus_ids:
            available = corpus_docs[corpus][:per_corpus_target]
            balanced_selection.extend(available)

        # Second pass: distribute remainder documents
        for i in range(remainder):
            if i < len(self._corpus_ids):
                corpus = self._corpus_ids[i]
                # Take next available document if we haven't exhausted this corpus
                if len(corpus_docs[corpus]) > per_corpus_target:
                    balanced_selection.append(corpus_docs[corpus][per_corpus_target])

        # Third pass: fill any remaining slots if we're still short
        if len(balanced_selection) < target_k:
            # Add unknown docs first
            for doc in unknown_docs:
                if len(balanced_selection) >= target_k:
                    break
                balanced_selection.append(doc)

            # Then take any remaining from corpus docs
            for corpus in self._corpus_ids:
                for doc in corpus_docs[corpus][per_corpus_target + 1:]:
                    if len(balanced_selection) >= target_k:
                        break
                    if doc not in balanced_selection:
                        balanced_selection.append(doc)

        return balanced_selection[:target_k]

    def _balanced_selection_from_categorized(self, corpus_docs: Dict[str, List[Document]], target_k: int) -> List[Document]:
        """
        Perform balanced selection from pre-categorized documents.

        Args:
            corpus_docs: Dictionary mapping corpus names to document lists
            target_k: Target number of documents to return

        Returns:
            Balanced selection of documents
        """
        # Remove empty corpora
        active_corpora = {k: v for k, v in corpus_docs.items() if v and k != "unknown"}

        if not active_corpora:
            # If no corpus-specific docs, return from unknown
            return corpus_docs.get("unknown", [])[:target_k]

        # Calculate documents per corpus
        corpora_count = len(active_corpora)
        per_corpus_target = target_k // corpora_count
        remainder = target_k % corpora_count

        # Build balanced selection
        balanced_selection = []

        # First pass: take target amount from each corpus
        for corpus, docs in active_corpora.items():
            available = docs[:per_corpus_target]
            balanced_selection.extend(available)

        # Second pass: distribute remainder documents
        corpus_names = list(active_corpora.keys())
        for i in range(remainder):
            if i < len(corpus_names):
                corpus = corpus_names[i]
                # Take next available document if we haven't exhausted this corpus
                if len(active_corpora[corpus]) > per_corpus_target:
                    balanced_selection.append(active_corpora[corpus][per_corpus_target])

        # Third pass: fill any remaining slots
        if len(balanced_selection) < target_k:
            # Add unknown docs first
            for doc in corpus_docs.get("unknown", []):
                if len(balanced_selection) >= target_k:
                    break
                balanced_selection.append(doc)

            # Then take any remaining from corpus docs
            for corpus, docs in active_corpora.items():
                for doc in docs[per_corpus_target + 1:]:
                    if len(balanced_selection) >= target_k:
                        break
                    if doc not in balanced_selection:
                        balanced_selection.append(doc)

        return balanced_selection[:target_k]

    async def _get_relevant_documents(
        self,
        query: str,
        **kwargs: Any,
    ) -> List[Document]:
        """
        Retrieve relevant documents with optional 2-filter filtering.

        Args:
            query: The search query
            **kwargs: Additional arguments including filters

        Returns:
            List of relevant documents
        """
        # Extract configuration
        config = kwargs.get("config", {})
        corpus_filter = config.get("corpus_filter")
        k = kwargs.get("k", self.search_kwargs.get("k", 20))

        # Check if we need balanced retrieval
        is_balanced_query = (not corpus_filter) or (corpus_filter == "all")

        # Enhanced filtering logic that works even when all docs have filter_1="all"
        if is_balanced_query:
            logger.info(f"Performing balanced retrieval across all corpora")

            # Get larger candidate pool for balanced selection
            candidate_k = self._candidate_pool_size(corpus_filter)
            logger.info(f"Searching with candidate_k={candidate_k}")

            all_docs = self.vector_store.similarity_search(
                query=query,
                k=candidate_k
            )
            logger.info(f"similarity_search returned {len(all_docs)} documents")

            # If all documents have filter_1="all", use source path to determine corpus
            if all_docs and all_docs[0].metadata.get("filter_1") == "all":
                logger.info("Documents have generic filter_1='all', using source path for corpus identification")

                # Categorize documents by actual corpus from source path
                corpus_docs = {"australia": [], "new_zealand": [], "united_kingdom": [], "unknown": []}

                for doc in all_docs:
                    source = doc.metadata.get("source", "").lower()
                    if "australia" in source:
                        corpus_docs["australia"].append(doc)
                    elif "new_zealand" in source or "new zealand" in source:
                        corpus_docs["new_zealand"].append(doc)
                    elif "united_kingdom" in source or "united kingdom" in source:
                        corpus_docs["united_kingdom"].append(doc)
                    else:
                        corpus_docs["unknown"].append(doc)

                # Log distribution
                for corpus, docs_list in corpus_docs.items():
                    if docs_list:
                        logger.info(f"  {corpus}: {len(docs_list)} documents")

                # Perform balanced selection from categorized documents
                docs = self._balanced_selection_from_categorized(corpus_docs, k)
            else:
                # Use filter_1 metadata for balanced selection (future corpora will have proper tags)
                # For now, just use the top k documents since proper corpus tags will be in future builds
                docs = all_docs[:k] if len(all_docs) > k else all_docs

            logger.info(f"Retrieved {len(docs)} documents with balanced selection")

        else:
            # Single corpus filtering
            logger.info(f"Filtering for specific corpus: '{corpus_filter}'")

            # Use larger candidate pool for single corpus
            candidate_k = self._candidate_pool_size(corpus_filter)
            logger.info(f"Searching for specific corpus '{corpus_filter}' with candidate_k={candidate_k}")

            # Get all documents first
            all_docs = self.vector_store.similarity_search(
                query=query,
                k=candidate_k
            )
            logger.info(f"similarity_search returned {len(all_docs)} documents")

            # Filter by corpus using source path if filter_1 is "all"
            if all_docs and all_docs[0].metadata.get("filter_1") == "all":
                logger.info("Using source path for corpus filtering since filter_1='all'")

                # Filter documents by source path
                filtered_docs = []
                corpus_lower = corpus_filter.lower().replace(" ", "_")

                for doc in all_docs:
                    source = doc.metadata.get("source", "").lower()
                    # Check various corpus name formats
                    if corpus_lower in ["australia", "aus"] and "australia" in source:
                        filtered_docs.append(doc)
                    elif corpus_lower in ["new_zealand", "nz", "new zealand"] and ("new_zealand" in source or "new zealand" in source):
                        filtered_docs.append(doc)
                    elif corpus_lower in ["united_kingdom", "uk", "united kingdom"] and ("united_kingdom" in source or "united kingdom" in source):
                        filtered_docs.append(doc)

                docs = filtered_docs[:k] if len(filtered_docs) > k else filtered_docs
                logger.info(f"Filtered to {len(docs)} documents from corpus '{corpus_filter}'")

                if not docs:
                    logger.warning(f"No documents found for corpus '{corpus_filter}', returning top matches from all")
                    docs = all_docs[:k]
            else:
                # Use filter_1 metadata (for future properly tagged corpora)
                filtered_docs = [doc for doc in all_docs if doc.metadata.get("filter_1") == corpus_filter]
                docs = filtered_docs[:k] if len(filtered_docs) > k else filtered_docs

            logger.info(f"Retrieved {len(docs)} documents for corpus: {corpus_filter}")

        # Log corpus distribution in final results
        if is_balanced_query and docs:
            corpus_dist = {}
            for doc in docs:
                corpus = doc.metadata.get("filter_1", doc.metadata.get("corpus", "unknown"))
                corpus_dist[corpus] = corpus_dist.get(corpus, 0) + 1
            logger.info(f"Final corpus distribution: {corpus_dist}")

        return docs

    def get_relevant_documents(
        self,
        query: str,
        **kwargs: Any,
    ) -> List[Document]:
        """
        Synchronous method to get relevant documents.
        Directly performs the search without async.
        """
        logger.info(f"get_relevant_documents called with query='{query[:50]}...', kwargs={kwargs}")

        # Extract configuration
        config = kwargs.get("config", {})
        corpus_filter = config.get("corpus_filter")
        k = kwargs.get("k", self.search_kwargs.get("k", 20))

        logger.info(f"Extracted config: corpus_filter='{corpus_filter}', k={k}")

        # Check if we need balanced retrieval
        is_balanced_query = (not corpus_filter) or (corpus_filter == "all")

        # Enhanced filtering logic that works even when all docs have filter_1="all"
        if is_balanced_query:
            logger.info(f"Performing balanced retrieval across all corpora")

            # Get larger candidate pool for balanced selection
            candidate_k = self._candidate_pool_size(corpus_filter)
            logger.info(f"Searching with candidate_k={candidate_k}")

            all_docs = self.vector_store.similarity_search(
                query=query,
                k=candidate_k
            )
            logger.info(f"similarity_search returned {len(all_docs)} documents")

            # If all documents have filter_1="all", use source path to determine corpus
            if all_docs and all_docs[0].metadata.get("filter_1") == "all":
                logger.info("Documents have generic filter_1='all', using source path for corpus identification")

                # Categorize documents by actual corpus from source path
                corpus_docs = {"australia": [], "new_zealand": [], "united_kingdom": [], "unknown": []}

                for doc in all_docs:
                    source = doc.metadata.get("source", "").lower()
                    if "australia" in source:
                        corpus_docs["australia"].append(doc)
                    elif "new_zealand" in source or "new zealand" in source:
                        corpus_docs["new_zealand"].append(doc)
                    elif "united_kingdom" in source or "united kingdom" in source:
                        corpus_docs["united_kingdom"].append(doc)
                    else:
                        corpus_docs["unknown"].append(doc)

                # Log distribution
                for corpus, docs_list in corpus_docs.items():
                    if docs_list:
                        logger.info(f"  {corpus}: {len(docs_list)} documents")

                # Perform balanced selection from categorized documents
                docs = self._balanced_selection_from_categorized(corpus_docs, k)
            else:
                # Use filter_1 metadata for balanced selection (future corpora will have proper tags)
                # For now, just use the top k documents since proper corpus tags will be in future builds
                docs = all_docs[:k] if len(all_docs) > k else all_docs

            logger.info(f"Retrieved {len(docs)} documents with balanced selection")

        else:
            # Single corpus filtering
            logger.info(f"Filtering for specific corpus: '{corpus_filter}'")

            # Use larger candidate pool for single corpus
            candidate_k = self._candidate_pool_size(corpus_filter)
            logger.info(f"Searching for specific corpus '{corpus_filter}' with candidate_k={candidate_k}")

            # Get all documents first
            all_docs = self.vector_store.similarity_search(
                query=query,
                k=candidate_k
            )
            logger.info(f"similarity_search returned {len(all_docs)} documents")

            # Filter by corpus using source path if filter_1 is "all"
            if all_docs and all_docs[0].metadata.get("filter_1") == "all":
                logger.info("Using source path for corpus filtering since filter_1='all'")

                # Filter documents by source path
                filtered_docs = []
                corpus_lower = corpus_filter.lower().replace(" ", "_")

                for doc in all_docs:
                    source = doc.metadata.get("source", "").lower()
                    # Check various corpus name formats
                    if corpus_lower in ["australia", "aus"] and "australia" in source:
                        filtered_docs.append(doc)
                    elif corpus_lower in ["new_zealand", "nz", "new zealand"] and ("new_zealand" in source or "new zealand" in source):
                        filtered_docs.append(doc)
                    elif corpus_lower in ["united_kingdom", "uk", "united kingdom"] and ("united_kingdom" in source or "united kingdom" in source):
                        filtered_docs.append(doc)

                docs = filtered_docs[:k] if len(filtered_docs) > k else filtered_docs
                logger.info(f"Filtered to {len(docs)} documents from corpus '{corpus_filter}'")

                if not docs:
                    logger.warning(f"No documents found for corpus '{corpus_filter}', returning top matches from all")
                    docs = all_docs[:k]
            else:
                # Use filter_1 metadata (for future properly tagged corpora)
                filtered_docs = [doc for doc in all_docs if doc.metadata.get("filter_1") == corpus_filter]
                docs = filtered_docs[:k] if len(filtered_docs) > k else filtered_docs

            logger.info(f"Retrieved {len(docs)} documents for corpus: {corpus_filter}")

        # Log corpus distribution in final results
        if is_balanced_query and docs:
            corpus_dist = {}
            for doc in docs:
                corpus = doc.metadata.get("filter_1", doc.metadata.get("corpus", "unknown"))
                corpus_dist[corpus] = corpus_dist.get(corpus, 0) + 1
            logger.info(f"Final corpus distribution: {corpus_dist}")

        return docs

    def invoke(self, query: str, config: Optional[Dict] = None, k: int = 10) -> List[Document]:
        """
        Synchronous method to retrieve documents.
        Directly calls the sync version.
        """
        logger.info(f"invoke called with query='{query[:50]}...', config={config}, k={k}")

        # Handle both config dict and k parameter
        kwargs = {}
        if config is not None:
            kwargs['config'] = config
        kwargs['k'] = k

        # Call get_relevant_documents with proper kwargs - don't suppress exceptions
        docs = self.get_relevant_documents(query=query, **kwargs)
        logger.info(f"invoke returning {len(docs)} documents")
        return docs