# Utility help targets
.PHONY: help-l help-c help-vs help-r help-xs

help-l:
	@echo "Generate requirements.lock file"
	@echo "Usage: make l"
	@echo ""
	@echo "This target generates a requirements.lock file:"
	@echo "1. Uses pip-tools to generate a lock file"
	@echo "2. Includes all dependencies with exact versions"
	@echo "3. Adds system-specific packages"
	@echo ""
	@echo "WARNING: The generated lock file is machine-specific!"
	@echo "Do not commit this file to version control."
	@echo ""
	@echo "For other systems:"
	@echo "- Ubuntu/Debian: Use requirements.lock.ubuntu"
	@echo "- macOS: Use requirements.lock.macos"
	@echo "- Windows: Use requirements.lock.windows"

help-c:
	@echo "Check Python environment"
	@echo "Usage: make c"
	@echo ""
	@echo "This target checks your Python environment:"
	@echo "1. Verifies Python version"
	@echo "2. Checks virtual environment"
	@echo "3. Reports any compatibility issues"
	@echo ""
	@echo "The recommended Python version is 3.11.5"
	@echo "Other versions may work but are not tested"

help-vs:
	@echo "Create vector store"
	@echo "Usage: make vs"
	@echo ""
	@echo "This target creates a vector store from Hansard TXT files:"
	@echo "1. Sets up a virtual environment"
	@echo "2. Installs required dependencies"
	@echo "3. Processes Hansard TXT files"
	@echo "4. Creates embeddings and stores them"
	@echo ""
	@echo "Required:"
	@echo "- Hansard TXT files in the correct location"
	@echo "- Sufficient disk space for the vector store"
	@echo "- Python 3.11.5 or compatible version"

help-r:
	@echo "Generate retriever"
	@echo "Usage: make r"
	@echo ""
	@echo "This target generates a retriever for the vector store:"
	@echo "1. Sets up a virtual environment"
	@echo "2. Installs required dependencies"
	@echo "3. Creates a retriever configuration"
	@echo "4. Tests the retriever"
	@echo ""
	@echo "Required:"
	@echo "- Vector store must exist"
	@echo "- Python 3.11.5 or compatible version"

help-xs:
	@echo "Create XML vector store"
	@echo "Usage: make xs"
	@echo ""
	@echo "This target creates a vector store from Hansard XML files:"
	@echo "1. Sets up a virtual environment"
	@echo "2. Installs required dependencies"
	@echo "3. Processes Hansard XML files"
	@echo "4. Creates embeddings and stores them"
	@echo ""
	@echo "Required:"
	@echo "- Hansard XML files in the correct location"
	@echo "- Sufficient disk space for the vector store"
	@echo "- Python 3.11.5 or compatible version"
	@echo ""
	@echo "After running:"
	@echo "1. Commit the database directory with Git LFS"
	@echo "2. Commit the retriever file with Git LFS"
	@echo "3. Update the retriever configuration if needed" 